.github/workflows/release-plz.yml
.github/workflows/release.yml
.github/workflows/rust.yml
Cargo.lock
Cargo.toml
Cross.toml
Dockerfile
clusters/local/Cargo.toml
clusters/sdn/Cargo.toml
deny.toml
packages/cluster/Cargo.toml
packages/endpoint/Cargo.toml
packages/media-utils/Cargo.toml
packages/media-utils/src/seq_extend.rs
packages/transport/Cargo.toml
servers/media/Cargo.toml
servers/sip-gateway/Cargo.toml
transports/rtmp/Cargo.toml
transports/sip/Cargo.toml
transports/sip/src/sip.rs
transports/sip/src/sip/utils.rs
transports/webrtc/Cargo.toml
transports/webrtc/benches/sdp_rewrite.rs

This PR fixing build releases and publish to github docker image

fix: auto build releases and publish docker

---

Cargo.lock
packages/cluster/src/define/rpc/gateway.rs
servers/media-server/Cargo.toml
servers/media-server/src/rpc/http.rs
servers/media-server/src/server.rs
servers/media-server/src/server/gateway.rs
servers/media-server/src/server/gateway/logic.rs
servers/media-server/src/server/gateway/logic/service.rs
servers/media-server/src/server/rtmp.rs
servers/media-server/src/server/webrtc.rs

- Added gateway dashboard
- Fix bug in media-server dashboard not update live sessions when session exited

fix: missing dashboard in gateway and live sessions not updated when session exit

---

.release-plz.toml
Cargo.toml
packages/cluster/Cargo.toml
packages/endpoint/Cargo.toml
packages/transport/Cargo.toml
servers/media-server/Cargo.toml
transports/rtmp/Cargo.toml
transports/sip/Cargo.toml
transports/webrtc/Cargo.toml

This PR fixing #122 and restructure workspace child crates

chore: restructure cargo workspace deps and fix #122

---

.github/workflows/release.yml
Cross.toml

This PR re-enable linux-musl-aarch64 build

Fix build aarch64 linux musl

---

packages/media_core/src/endpoint.rs
packages/media_core/src/endpoint/internal.rs
packages/media_core/src/endpoint/internal/bitrate_allocator.rs
packages/media_core/src/endpoint/internal/bitrate_allocator/egress.rs
packages/media_core/src/endpoint/internal/bitrate_allocator/ingress.rs
packages/media_core/src/endpoint/internal/local_track.rs
packages/media_core/src/endpoint/internal/remote_track.rs
packages/media_core/src/transport.rs
packages/protocol/src/endpoint.rs
packages/transport_webrtc/src/transport.rs
packages/transport_webrtc/src/transport/bwe_state.rs
packages/transport_webrtc/src/transport/whip.rs
packages/transport_webrtc/src/worker.rs

This PR implement bitrate allocator for both egress and ingress, this is prepares for SDK implementation

feat: bitrate allocator with both egress and ingress.

---

README.md

This PR switch webrtc sdk status from dev to inreview/testing

chore: update readme for webrtc sdk status

---

README.md
packages/media_gateway/src/store.rs
packages/media_gateway/src/store/service.rs
packages/media_secure/src/jwt.rs
packages/media_secure/src/lib.rs

This PR add more tests for gateway logic

test: registry store

---

packages/media_gateway/src/store.rs

This PR fixed wrong compare between memory and cpu MAX

fixed: media gateway wrong cpu and memory compare

---

Cargo.lock
Cargo.toml

This PR updates the sdn library for fixing reconnect unsuccessful bug

Fix reconnect unsuccessful

---

Cargo.lock
bin/Cargo.toml
packages/media_gateway/Cargo.toml
packages/protocol/Cargo.toml

This PR updates deps by "cargo update"

deps: run cargo update

---

.github/workflows/release.yml
bin/Cargo.toml
packages/media_record/Cargo.toml
packages/media_record/src/lib.rs

This PR fixed errror when build release with github action in musl target.

fixed: build release with github action

---

.github/workflows/release.yml
Cargo.lock
packages/media_core/src/endpoint/internal.rs
packages/media_record/Cargo.toml
packages/media_record/bin/convert_record.rs
packages/media_record/src/lib.rs
packages/media_record/src/media.rs
packages/media_record/src/media/vpx_writer.rs
packages/media_record/src/storage/mod.rs

This PR update convert_webm into convert_record with some changes (#346):
- each track become separated media file
- option to push to s3

feat: convert record to separated media files and push to s3

---

bin/src/http/api_token.rs

This PR turn record params to optional

turn record params to optional in API

---

Cargo.lock
Cargo.toml
bin/src/lib.rs
bin/src/main.rs
bin/src/server/connector.rs
bin/src/server/console.rs
bin/src/server/gateway.rs
bin/src/server/media/runtime_worker.rs
packages/media_runner/Cargo.toml
packages/media_runner/src/worker.rs
packages/transport_webrtc/Cargo.toml

This PR switch internal deps (atm0s-sdn and sans-io-runtime) from git to crates.io

deps: switched to internal deps from crate.io

---

README.md
bin/console.sh
bin/gate_z0_n1.sh
bin/gate_z256_n1.sh
bin/media_z0_n2.sh
bin/media_z0_n3.sh
bin/media_z256_n1.sh
bin/media_z256_n2.sh
bin/src/lib.rs
bin/src/main.rs
bin/src/server/connector.rs
bin/src/server/console.rs
bin/src/server/gateway.rs
bin/src/server/media.rs
bin/src/server/media/runtime_worker.rs
docs/getting-started/installation/single-zone.md
packages/media_runner/src/worker.rs
packages/transport_webrtc/src/transport.rs
packages/transport_webrtc/src/worker.rs

This PR fix crash bug when some sdn-addr cannot successfully bind or start with more than one worker

fix: unsuccessful bind addr cause crash media node

---

docs/getting-started/installation/single-zone.md

Typo correction

---

Cargo.lock

This PR update deps with cargo update

deps: update with cargo update

---

Cargo.lock
bin/Cargo.toml
bin/src/main.rs

This PR add error feedback to sentry endpoint

feat: added sentry crash report, added cli opts for disable or custom sentry endpoint

---

bin/src/server/connector/remote_rpc_handler.rs
packages/media_connector/src/lib.rs
packages/media_connector/src/sql_storage.rs
packages/media_connector/src/sql_storage/entity/event.rs
packages/media_connector/src/sql_storage/migration.rs
packages/media_connector/src/sql_storage/migration/m20240809_0001_change_node_id_i64.rs

This PR fix sea-orm model for working with postgresql

fixed: postgresql query error

---

packages/media_connector/src/sql_storage/migration/m20240824_0001_add_room_destroy_and_record.rs

This PR fix a migration failed to run with mysql backend

fix: migration failed with mysql database

---

Cargo.lock
deny.toml
rust-toolchain.toml

deps: cargo update

---

Cargo.lock

This PR update SDN to 0.2.4 with node router dump feature.

deps: update sdn version

---

bin/src/main.rs

This PR fixed "node is connect to itself with seeds config". It will have some strange route table

fix: don't connect itself

---

Cargo.lock

This PR update deps with cargo update for updating outdate libc dependency.

deps: update

---

packages/media_console_front/build.rs
packages/media_console_front/src/dev_proxy.rs
packages/media_console_front/src/lib.rs
packages/media_utils/src/embed_files.rs

fix some clippy warns

---

bin/Cargo.toml
packages/audio_mixer/Cargo.toml
packages/media_codecs/Cargo.toml
packages/media_connector/Cargo.toml
packages/media_console_front/Cargo.toml
packages/media_core/Cargo.toml
packages/media_gateway/Cargo.toml
packages/media_record/Cargo.toml
packages/media_runner/Cargo.toml
packages/media_secure/Cargo.toml
packages/media_utils/Cargo.toml
packages/multi_tenancy/Cargo.toml
packages/protocol/Cargo.toml
packages/transport_rtpengine/Cargo.toml
packages/transport_webrtc/Cargo.toml

chore: update metadata for packages

---

Cargo.lock
bin/Cargo.toml
bin/src/node_metrics.rs
deny.toml

Switch to pure-rust systemstat

feat: switched to pure-rust systemstat

---

packages/media_console_front/src/lib.rs

Console node stuck forever in `pnpm run`

fix: console node stuck in dev mode

---

Cargo.lock
Cargo.toml
bin/Cargo.toml
packages/audio_mixer/Cargo.toml
packages/media_utils/Cargo.toml
packages/transport_webrtc/Cargo.toml

chore: update version for release-plz

---

Cargo.lock
Cargo.toml
packages/protocol/Cargo.toml

Update packages version for release-plz

chore: update version for release-plz patch2

---

.github/workflows/release.yml

Wrong package name in github action build record tools

fix: build record tool error in github action release

---

packages/media_record/Cargo.toml

fix: record tool missing opus deps

---

.github/workflows/release.yml

Restore github ci config for building on release

chore: fix github ci build on release

---

.github/workflows/release-plz.yml

switch release-plz to PAT token for triggering release action

chore: switch release-plz to PAT token for triggering release action

---

.github/workflows/release.yml
Dockerfile

This PR update build env to ubuntu 24.04 for release version

Ci update docker build action

---

Cargo.lock
bin/src/http/utils/payload_protobuf.rs
bin/src/http/utils/payload_sdp.rs

This PR update atm0s-sdn for fixing network unstable issue after some node disconnected.
https://github.com/8xFF/atm0s-sdn/pull/192

deps: update atm0s-sdn for fixing network unstable issue

---

Cargo.lock
Cargo.toml
packages/media_runner/src/worker.rs

This PR fix wrong worker-id setting, this can cause another issue with stream subscribe

fix: wrong worker setting cause cross nodes stream subscribe failed
