Cargo.lock
Update Cargo.lock for updating to newest atm0s-sdn
=> chore: update atm0s-sdn libs

.github/workflows/release-plz.yml, transports/sip/Cargo.toml
Set publish=false for transport-sip and add bellow deps in release-plz
```yaml
- name: Install dev-tools
run: sudo apt-get install -y --no-install-recommends pkg-config musl-dev musl-tools
- name: Install deps
run: sudo apt-get install -y --no-install-recommends libssl-dev libopus-dev libfdk-aac-dev libsoxr-dev
```
=> chore: temporal set publish=false sip transport

.release-plz.toml, Cargo.lock, Cargo.toml, packages/audio-mixer/Cargo.toml, packages/audio-mixer/src/lib.rs, packages/audio-mixer/src/mixer.rs, packages/cluster/src/define/local_track.rs, packages/cluster/src/define/mod.rs, packages/cluster/src/implement/endpoint.rs, packages/endpoint/Cargo.toml, packages/endpoint/src/endpoint_pre.rs, packages/endpoint/src/endpoint_wrap.rs, packages/endpoint/src/endpoint_wrap/internal.rs, packages/endpoint/src/endpoint_wrap/internal/local_track.rs, packages/endpoint/src/endpoint_wrap/internal/remote_track.rs, packages/endpoint/src/middleware.rs, packages/endpoint/src/middleware/logger.rs, packages/endpoint/src/middleware/mix_minus.rs, packages/media-utils/src/seq_rewrite.rs, packages/media-utils/src/ts_rewriter.rs, packages/transport/src/packet.rs, servers/media-server/src/server/rtmp/session.rs, servers/media-server/src/server/sip/sip_in_session.rs, servers/media-server/src/server/sip/sip_out_session.rs, servers/media-server/src/server/webrtc.rs, servers/media-server/src/server/webrtc/session.rs, transports/webrtc/src/transport/internal.rs, transports/webrtc/src/transport/rtp_packet_convert.rs
This PR implements an audio mixer with a mix-minus mechanism. This allows for semi-mixed audio in large conference rooms without decoding and encoding audio codecs.
The main idea is to select the tracks with the highest audio levels and send them to the client. These tracks are automatically switched on the server side without any control from the client. Additionally, the client can adjust which source track they are interested in, which is very useful in open-workspace applications like Gather.town.
=> WIP: audio mix-minus

transports/webrtc/src/transport.rs, transports/webrtc/src/transport/internal.rs, transports/webrtc/src/transport/internal/local_track_id_generator.rs, transports/webrtc/src/transport/life_cycle/whep.rs, transports/webrtc/src/transport/mid_convert.rs, transports/webrtc/src/transport/str0m_event_convert.rs
This PR fix webrtc track_id rule by mapping Mid [u8; 16] in a HashMap. Previously version convert directly [u8; 16] to u16 that cannot work correctly with random Mid, which is used by some webrtc-client
=> fix: wrong track_id convert from random webrtc Mid

packages/endpoint/src/endpoint_wrap.rs, packages/endpoint/src/endpoint_wrap/internal.rs, packages/endpoint/src/rpc.rs, transports/webrtc/src/transport/internal/rpc.rs
This PR introduces a room scope mode for each endpoint. There are two modes:
- Auto: All peer and track events will be fired to the endpoint.
- Manual: Only subscribed peers will trigger events at the endpoint.
This feature is particularly useful for creating an online event platform like Gather.town. We're only interested in certain users nearby. When a user is close, we'll call room.subscribe(peer_id), and when they're far away, we'll call room.unsubscribe(peer_id).
=> feat: auto or manual peer info subscribe

packages/cluster/src/define/rpc/webrtc.rs, servers/media-server/src/rpc/http.rs, servers/media-server/src/rpc/http/payload_sdp.rs, servers/media-server/src/server/gateway/rpc/http.rs, servers/media-server/src/server/webrtc/rpc/http.rs, transports/webrtc/src/transport/internal.rs, transports/webrtc/src/transport/internal/utils.rs
This PR fix issue #176
Changes:
- Allow "application/trickle-ice-sdpfrag" payload-type
- Process ice-remote candidates from patch request
=> fix: whip/whep sdp patch with client ices failed #176

.release-plz.toml
This PR setting release-plz config for setting release name and tag name as "v{{ version }}" style
No
=> chore: config release name to v{{ version }} style

README.md, packages/media_core/src/cluster.rs, packages/media_core/src/cluster/id_generator.rs, packages/media_core/src/cluster/room.rs, packages/media_core/src/cluster/room/channel_pub.rs, packages/media_core/src/cluster/room/channel_sub.rs, packages/media_core/src/cluster/room/metadata.rs
This PR implement logic for pubsub channel with feedback: Bitrate Limit and Key Frame request. This also added more tests
=> feat: channel pub-sub feature and tests. cluster integration test

Cargo.lock, bin/src/server/media.rs, packages/media_core/src/endpoint.rs, packages/media_core/src/endpoint/internal.rs, packages/media_core/src/endpoint/internal/bitrate_allocator.rs, packages/media_core/src/endpoint/internal/local_track.rs, packages/media_core/src/endpoint/internal/remote_track.rs, packages/media_core/src/transport.rs, packages/protocol/src/endpoint.rs, packages/protocol/src/media.rs, packages/transport_webrtc/Cargo.toml, packages/transport_webrtc/src/transport.rs, packages/transport_webrtc/src/transport/bwe_state.rs, packages/transport_webrtc/src/transport/whep.rs, packages/transport_webrtc/src/transport/whip.rs, packages/transport_webrtc/src/worker.rs
This PR implement bitrate control with Twcc and Remb
=> feat: bitrate control with Twcc and Remb

packages/media_core/src/cluster.rs, packages/media_core/src/cluster/room.rs
This PR fix missing clear room_map in cluster cause room failed to restart
=> fix: missing clear room_map in cluster cause room failed to restart

README.md
This PR updates the status of some features:
- Room & Peer: 🚀
- Whip: 🚀
- Whep: 🚀
- Simulcast & Svc: 🚀
=> chore: update feature status in README

Cargo.lock, README.md, bin/Cargo.toml, bin/src/errors.rs, bin/src/lib.rs, bin/src/node_metrics.rs, bin/src/server/gateway.rs, bin/src/server/gateway/dest_selector.rs, bin/src/server/gateway/local_rpc_handler.rs, bin/src/server/gateway/remote_rpc_handler.rs, bin/src/server/media.rs, bin/src/server/media/runtime_worker.rs, packages/media_gateway/src/agent_service.rs, packages/media_gateway/src/lib.rs, packages/media_gateway/src/store.rs, packages/media_gateway/src/store_service.rs, packages/media_runner/src/worker.rs
This PR implement node metric feedback mechanism for supporting gateway routing
=> Feat ping with node usage

Cargo.toml, bin/src/http/api_console.rs, bin/src/http/api_console/connector.rs, bin/src/quinn/vnet.rs, bin/src/server/connector.rs, bin/src/server/console/storage.rs, bin/src/server/gateway.rs, bin/src/server/media.rs, bin/src/server/media/runtime_worker.rs, packages/audio_mixer/src/lib.rs, packages/media_connector/src/agent_service.rs, packages/media_connector/src/handler_service.rs, packages/media_connector/src/msg_queue.rs, packages/media_connector/src/sql_storage/migration/m20240626_0001_init.rs, packages/media_core/src/cluster/room/audio_mixer.rs, packages/media_core/src/cluster/room/audio_mixer/manual.rs, packages/media_core/src/endpoint/internal.rs, packages/media_core/src/endpoint/internal/local_track/packet_selector/video_h264_sim.rs, packages/media_core/src/endpoint/internal/local_track/packet_selector/video_vp8_sim.rs, packages/media_core/src/endpoint/internal/local_track/packet_selector/video_vp9_svc.rs, packages/media_core/src/endpoint/internal/remote_track.rs, packages/media_gateway/src/agent_service.rs, packages/media_runner/src/worker.rs, packages/media_secure/src/jwt.rs, packages/transport_webrtc/src/media/vp9.rs, packages/transport_webrtc/src/transport.rs, packages/transport_webrtc/src/transport/webrtc.rs, rust-toolchain.toml
Fix Cargo Build Warning and Clippy Warnings
=> Fix build warnings and clippy warnings

.github/workflows/release.yml
This PR fixed build release failed caused by missing musl-c++
Github Actions build release failed
=> Fix: build release with c++ deps

bin/src/server/connector/remote_rpc_handler.rs, packages/media_connector/src/lib.rs, packages/media_connector/src/sql_storage.rs
This PR fix wrong created_at filed in log sessions api response
=> fix: wrong between created_at and session_id in sessions api

.github/workflows/rust-clippy.yml, .github/workflows/rust-fmt.yml, .github/workflows/rust.yml, bin/src/http.rs, packages/media_core/src/cluster.rs, packages/media_core/src/endpoint/internal/local_track/packet_selector/video_vp8_sim.rs, packages/media_core/src/endpoint/internal/local_track/packet_selector/video_vp9_svc.rs, packages/media_record/src/storage/disk.rs, packages/media_record/src/storage/memory.rs, packages/media_utils/src/f16.rs, packages/protocol/build.rs, packages/transport_webrtc/src/media/vp8.rs
Clippy was already being used. But it never reported any problems. The errors were always suppressed because we were piping the clippy output to cargo-sarif. This piping masked the exit code of clippy command. Which is why you might notice clippy is run twice now.
Note: actions-rs was deprecated and archived because GH Actions now support for rust by default: https://github.com/actions/starter-workflows/blob/main/ci/rust.yml
Apart from this, I have also added a cargo fmt action, added cache support and fixed remaining clippy warnings.
CC: @giangndm: https://github.com/8xFF/atm0s-media-server/pull/349#issuecomment-2232288594
=> ci: fix clippy actions workflow and add cargo-fmt action

Cargo.lock, bin/src/http/api_console/connector.rs, bin/src/server/connector/remote_rpc_handler.rs, packages/media_connector/Cargo.toml, packages/media_connector/src/sql_storage.rs, packages/protocol/proto/cluster/connector.proto, packages/protocol/src/protobuf/cluster_connector.rs
This PR fix missing data in bellow apis:
- peers log
- sessions log
N/A
Currently sea-orm don't support two find_with_related then we need collect data in multiple queries, should fix in future
=> fix: api missing data

packages/media_core/src/cluster/room/media_track/publisher.rs
=> fix: server crash if two sessions leaved with same room peer

bin/src/http/api_media.rs, bin/src/http/api_token.rs, bin/src/server/gateway/local_rpc_handler.rs, bin/src/server/media/rpc_handler.rs, bin/src/server/media/runtime_worker.rs, docs/user-guide/features/README.md, docs/user-guide/features/userdata-metadata.md, packages/media_core/src/cluster.rs, packages/media_core/src/cluster/room.rs, packages/media_core/src/cluster/room/metadata.rs, packages/media_core/src/endpoint/internal.rs, packages/media_runner/src/worker.rs, packages/protocol/proto/cluster/gateway.proto, packages/protocol/proto/sdk/session.proto, packages/protocol/src/endpoint.rs, packages/protocol/src/protobuf/cluster_gateway.rs, packages/protocol/src/protobuf/session.rs, packages/protocol/src/tokens.rs, packages/protocol/src/transport/webrtc.rs, packages/protocol/src/transport/whep.rs, packages/protocol/src/transport/whip.rs, packages/transport_webrtc/src/transport.rs, packages/transport_webrtc/src/transport/webrtc.rs, packages/transport_webrtc/src/transport/whep.rs, packages/transport_webrtc/src/transport/whip.rs, packages/transport_webrtc/src/worker.rs
This PR allow embedded static userdata into peer token, which allow more flexible when integrate with 3rd system
Now we can set userdata field when create whip, whep or webrtc token.
=> feat: embedded userdata to token

packages/media_core/src/endpoint/internal.rs, packages/media_core/src/endpoint/internal/local_track.rs, packages/media_core/src/endpoint/internal/remote_track.rs
This PR fix server crash if remote stream is released
=> fixed: server crash because wrong ordered of remote stream destroy messages

packages/media_core/src/endpoint.rs, packages/media_core/src/transport.rs, packages/media_runner/src/worker.rs, packages/transport_webrtc/src/transport.rs, packages/transport_webrtc/src/transport/webrtc.rs, packages/transport_webrtc/src/worker.rs
This PR add graceful disconnect for webrtc connections. incoming request waits for internal endpoint destroyed before response to client
=> Feat graceful disconnect webrtc

bin/src/http/api_media.rs, bin/src/http/api_token.rs, bin/src/server/gateway/local_rpc_handler.rs, bin/src/server/media/rpc_handler.rs, docs/user-guide/features/README.md, docs/user-guide/features/extra_data-metadata.md, docs/user-guide/features/userdata-metadata.md, packages/media_core/src/cluster.rs, packages/media_core/src/cluster/room.rs, packages/media_core/src/cluster/room/metadata.rs, packages/media_core/src/endpoint/internal.rs, packages/media_runner/src/worker.rs, packages/protocol/proto/cluster/gateway.proto, packages/protocol/proto/sdk/session.proto, packages/protocol/src/endpoint.rs, packages/protocol/src/protobuf/cluster_gateway.rs, packages/protocol/src/protobuf/session.rs, packages/protocol/src/tokens.rs, packages/protocol/src/transport/webrtc.rs, packages/protocol/src/transport/whep.rs, packages/protocol/src/transport/whip.rs, packages/transport_webrtc/src/transport.rs, packages/transport_webrtc/src/transport/webrtc.rs, packages/transport_webrtc/src/transport/whep.rs, packages/transport_webrtc/src/transport/whip.rs, packages/transport_webrtc/src/worker.rs
This PR rename from peer's userdata to peer's extra_data for avoiding mis-understanding
=> fefactor: rename userdata to extra data

packages/transport_webrtc/src/transport.rs
This PR fixed connect error with Firefox, it only works after https://github.com/8xFF/atm0s-media-sdk-ts/pull/18 is merged
=> fixed: firefox webrtc don't work with channel id 1000, switch back to 0

packages/media_runner/src/worker.rs
This PR fixed missing peer logs issue.
The main reason is config for connector agent is only set for controller thread, not worker thread.
https://github.com/8xFF/atm0s-media-server/blob/9b1403b1eecef5faf000eb9820b8022d2a1da53f/packages/media_runner/src/worker.rs#L176-L197
(at line 194 we missed "connector")
This only occurred after we have some optimized by avoiding internal event re-router to controller then back to worker.
=> fixed: missing config connector agent service which caused missing peer logs

Cargo.lock, bin/media_z0_n2.sh, bin/media_z0_n3.sh, bin/media_z256_n1.sh, bin/media_z256_n2.sh, bin/src/errors.rs, bin/src/server/gateway.rs, bin/src/server/gateway/dest_selector.rs, bin/src/server/gateway/local_rpc_handler.rs, packages/media_gateway/Cargo.toml, packages/media_gateway/src/store.rs, packages/media_gateway/src/store/service.rs, packages/media_gateway/src/store_service.rs, packages/media_utils/src/lib.rs, packages/media_utils/src/sdn.rs
This PR implement node fallback with restart-ice request for allowing reconnect to other node.
Re-route Flow:
- If dest-node is same zone with gateway -> return Some(dest) if online
- If dest-node is other zone -> find dest zone gateway and return Some(gateway_node) if available
If no dest found (node or gateway), then select from pool based on client IP
https://github.com/8xFF/atm0s-media-server/issues/383
=> fixed: route restart-ice to other media node if current down

bin/connector_z0_n1.sh, bin/connector_z256_n1.sh, bin/src/http/api_console/cluster.rs, bin/src/lib.rs, bin/src/main.rs, bin/src/server/console/storage.rs, bin/src/server/gateway.rs, bin/src/server/media.rs, bin/z0_connector_n4.sh, bin/z0_console_n0.sh, bin/z0_gate_n1.sh, bin/z0_media_n2.sh, bin/z0_media_n3.sh, bin/z1_connector_n4.sh, bin/z1_gate_n1.sh, bin/z1_media_n2.sh, bin/z1_media_n3.sh, docs/getting-started/installation/docker-compose.md, docs/getting-started/installation/multi-zones.md, docs/getting-started/installation/single-zone.md, packages/media_gateway/src/store.rs, packages/media_gateway/src/store/service.rs, packages/media_gateway/src/store_service.rs, packages/media_runner/src/worker.rs, packages/media_utils/src/lib.rs, packages/media_utils/src/sdn.rs, packages/protocol/src/cluster.rs, packages/protocol/src/gateway.rs, packages/rtpengine_ngcontrol/src/transport/udp.rs
This PR updates the SDN configuration. Changed form u32 sdn-zone, node-id to 
- u24 sdn-zone-id: what every you chose for zone_id (but should be smallest as possible for routing efficiency) 
- u8 sdn-zone-node-id: from 0 to 255, which mean you have maximum 256 node in a single zones
https://github.com/8xFF/atm0s-media-server/issues/409
=> refactor: config zone id node id media port, get console lists

bin/src/main.rs
This PR switched sentry reporting to optional for privacy issue
=> chore: switched sentry error reporting to optional

packages/transport_webrtc/src/media/h264.rs
This PR fixed missing for handling non-simulcast h264 video packet.
=> fix: obs failed to publish video

bin/src/server/connector.rs, bin/src/server/gateway.rs, bin/src/server/media.rs, docs/user-guide/integration.md, packages/multi_tenancy/src/store.rs
This PR updates the multi tenancy feature configuration. Now we have 2 separated mode:
- Single app only with static secret
- Dynamic (multi-tenancy) apps if app sync url is provided with gateway and connector.
No
=> feat: now we have 2 mode: multi-tenancy with dynamic app sync or static secret

docs/user-guide/features/recording.md, packages/media_record/bin/convert_record_worker.rs, packages/media_record/src/convert.rs, packages/media_record/src/convert/codec/vpx_writer.rs, packages/media_record/src/convert/composer.rs, packages/media_record/src/convert/composer/audio_mixer/mixer_buffer.rs, packages/protocol/proto/cluster/connector.proto, packages/protocol/src/protobuf/cluster_connector.rs
This PR add duration_ms to record compose output
=> feat: add duration_ms to compose record result

packages/media_core/src/endpoint/internal/local_track/packet_selector.rs, packages/media_core/src/endpoint/internal/local_track/packet_selector/video_h264_sim.rs, packages/media_core/src/endpoint/internal/local_track/packet_selector/video_vp8_sim.rs, packages/media_core/src/endpoint/internal/local_track/packet_selector/video_vp9_svc.rs, packages/media_record/src/convert/codec/vpx_demuxer.rs, packages/protocol/proto/record/file_rec.proto, packages/protocol/src/media.rs, packages/transport_webrtc/src/media/h264.rs, packages/transport_webrtc/src/media/mod.rs, packages/transport_webrtc/src/media/vp8.rs, packages/transport_webrtc/src/media/vp9.rs, packages/transport_webrtc/src/transport.rs
This PR add logic for supporting video orientation extension from WebRTC
=> fix: handle video orientation from webrtc-extension

packages/media_core/src/endpoint.rs, packages/transport_webrtc/src/transport/webrtc.rs, packages/transport_webrtc/src/transport/whep.rs, packages/transport_webrtc/src/transport/whip.rs
This PR fix webrtc transport close stuck on connect_error, this cause memory leak bug
=> fix: webrtc transport stuck on connect_error cause memory leak

bin/Cargo.toml, bin/media_single.sh, bin/src/main.rs, bin/src/server.rs, bin/src/server/connector.rs, bin/src/server/console.rs, bin/src/server/gateway.rs, bin/src/server/media.rs, bin/src/server/standalone.rs, bin/standalone.sh, docs/getting-started/installation/README.md, docs/getting-started/installation/standalone.md, packages/media_runner/src/worker.rs
This PR create standalone mode, which starts all modules automatically with only local ip:
- console
- gateway
- 2 media
- connector
=> feat: standlone server

packages/media_codecs/src/pcma.rs
Sometime we received strange rtp packet with 200 bytes instead of 160 bytes => reject if != 160 bytes
=> fix: pcma decode crash

packages/media_gateway/src/store.rs
This PR fixed bug: media-gateway missing clear rtpengine timeout, this cause sometime rtpengine request timeout
=> fix: media-gateway rtpengine missing clear timeout

bin/src/main.rs
This PR add --enable-interfaces config for allowing filter which network interface will be used. If it not set, it mean all of interfaces is allowed
=> feat: added config for filter binding address by interface name

bin/src/server/connector.rs, packages/media_connector/src/handler_service.rs, packages/media_connector/src/lib.rs, packages/media_connector/src/sql_storage.rs
When a request send from media to connector but connector failed to process, media-server will try forever. It can be fix by only marked it as processed it it success process on connector
=> fix: some time connector handle duplicate incorrect, ensure it success

packages/transport_rtpengine/src/transport.rs
This PR increase rtp timeout to 3 minutes for avoiding timeout before SIP call drop
=> fix: increase rtp timeout to 3 minutes

.github/workflows/release.yml
This PR stick to ubuntu 22.04 for building release
=> ci: force ubuntu 22.04 build release

Cargo.lock, packages/media_record/Cargo.toml
=> deps: switch rusty-s3 to crates instead of git

bin/Cargo.toml
media-server-secure missed "jwt-secure" feature.
=> fix: missing media-server-secure feature which caused build media-server error

Cargo.lock, Cargo.toml, bin/CHANGELOG.md, bin/Cargo.toml, packages/media_codecs/CHANGELOG.md, packages/media_codecs/Cargo.toml, packages/media_console_front/CHANGELOG.md, packages/media_console_front/Cargo.toml, packages/media_record/CHANGELOG.md, packages/media_record/Cargo.toml, packages/transport_rtpengine/CHANGELOG.md, packages/transport_rtpengine/Cargo.toml
* `atm0s-media-server-console-front`: 0.1.0-alpha.1 -> 0.1.0-alpha.2 (✓ API compatible changes)
* `atm0s-media-server-codecs`: 0.1.0-alpha.1 -> 0.1.0-alpha.2 (✓ API compatible changes)
* `atm0s-media-server`: 0.2.0-alpha.3 -> 0.2.0-alpha.4 (⚠ API breaking changes)
* `atm0s-media-server-record`: 0.1.0-alpha.1 -> 0.1.0-alpha.2
* `atm0s-media-server-transport-rtpengine`: 0.1.0-alpha.2 -> 0.1.0-alpha.3
```text
--- failure auto_trait_impl_removed: auto trait no longer implemented ---
Description:
A public type has stopped implementing one or more auto traits. This can break downstream code that depends on the traits being implemented.
ref: https://doc.rust-lang.org/reference/special-types-and-traits.html#auto-traits
impl: https://github.com/obi1kenobi/cargo-semver-checks/tree/v0.39.0/src/lints/ …
```
=> chore: release

Cargo.lock
This PR updates the sdn dependencies to version 0.2.7 to fix the dht-kv clearing issue. This issue affected the media server, causing videos not to display after rejoining the same server.
=> deps: update sdn for fixing video not to display after rejoining

Cargo.lock, Cargo.toml, bin/CHANGELOG.md, bin/Cargo.toml, packages/media_console_front/CHANGELOG.md, packages/media_console_front/Cargo.toml, packages/media_record/CHANGELOG.md, packages/media_record/Cargo.toml, packages/media_runner/CHANGELOG.md, packages/media_runner/Cargo.toml
* `atm0s-media-server-console-front`: 0.1.0-alpha.2 -> 0.1.0-alpha.3 (✓ API compatible changes)
* `atm0s-media-server-record`: 0.1.0-alpha.3 -> 0.1.0-alpha.4 (✓ API compatible changes)
* `atm0s-media-server-runner`: 0.1.0-alpha.2 -> 0.1.0-alpha.3 (✓ API compatible changes)
* `atm0s-media-server`: 0.2.0-alpha.5 -> 0.2.0-alpha.6 (✓ API compatible changes)
<details><summary><i><b>Changelog</b></i></summary><p>
<blockquote>
- migrate to tailwindcss v4, update layout, router ([#514](https://github.com/8xFF/atm0s-media-server/pull/514))
</blockquote>
<blockquote>
- update Cargo.lock dependencies
</blockquote>
<blockquote>
- wrong worker setting cause cross nodes stream subscribe failed ([#517](https://github.com/8xFF/atm0s-media-server/pull/517))
</blockquote>
<blockquote>
- wrong worker …
=> chore: release 0.2.0-alpha.6

bin/src/server/media.rs
This PR change vnet to stick on worker 0 for avoiding actor miss-matched. This issue started when we fixed wrong worker config with PR https://github.com/8xFF/atm0s-media-server/pull/517
=> fix: vnet should stick on same worker for avoiding actor missmatch error
